### ISSUE TITLE
Large Images

### ISSUE THREAD

**Issue by suukit** [DirkNachbar/Docker#3]
Hi,
I refactored some of the build code to get smaller images. (5.57GB for localhost/oracle/formsreports:12.2.1.3). Someone interested?

best regards
Max

**Comment by hollipolli2904** [comment]
Off course yes :-)

+1

**Comment by suukit** [comment]
I just added code for version 12.2.1.3 of FMWInfratructure and FormsReports.  Should I open a branch for this incomplete code?

**Comment by suukit** [comment]
If you want to try: https://github.com/suukit/Docker

**Comment by hollipolli2904** [comment]
I've tried it and after some modifications it was good :-)

Without the sources the images were nearly as @suukit mentioned.
